gazebo_ros_control/pid_gains:
  slide: {p: 0.1, i: 0.0, d: 0.02}
  shoulder_pan_joint: {p: 0.1, i: 0.0, d: 0.02}
  shoulder_lift_joint: {p: 0.1, i: 0.0, d: 0.02}
  elbow_joint: {p: 0.1, i: 0.0, d: 0.02}
  wrist_1_joint: {p: 0.1, i: 0.0, d: 0.02}
  wrist_2_joint: {p: 0.1, i: 0.0, d: 0.02}
  wrist_3_joint: {p: 0.1, i: 0.0, d: 0.02}
  finger_joint: {p: 0.1, i: 0.0, d: 0.02}

